### PR TITLE
Lighting Section

### PR DESCRIPTION
**Pull request by pigpenguin**
A couple of small changes (removing spans, adding links to the workshop pages for maps referenced, added a favicon)

Bigger changes: Added a section about the three different types of lightings and corrected a small issue in the performance section.

### CODE REVIEW

**Comment by tesselode** [comment]
Very nice! Hey, do you want to take over the project for me? I haven't really played Distance or done anything Distance-related in a long time.

**Comment by pigpenguin** [comment]
I'd be happy to

**Comment by pigpenguin** [comment]
Should I just run with my current branch and stop sending pull requests then? (I already have a copy being hosted [here](http://distance.pigpenguin.com) to test the changes I make and could just continue doing that)

**Comment by tesselode** [comment]
That could work. I believe GitHub has a way to transfer projects to another person, but that's not necessary when you can just start calling your fork the official one. If you do want to do something else, though, let me know.

**Pull request merged**
